# Generated by Django 5.2.3 on 2025-06-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_group'),
        ('shared_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='events.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shared_resources.sharedresource')),
            ],
            options={
                'db_table': 'EventResources',
                'unique_together': {('event', 'resource')},
            },
        ),
    ]
