# Generated by Django 5.2.3 on 2025-06-18 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_sent', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user1', 'user2'], name='IDX_Friendships_Users')],
                'constraints': [models.UniqueConstraint(fields=('user1', 'user2'), name='UC_Friendship_Users'), models.CheckConstraint(condition=models.Q(('user1', models.F('user2')), _negated=True), name='CHK_Different_Users'), models.CheckConstraint(condition=models.Q(('user1__lt', models.F('user2'))), name='CHK_User_Order')],
            },
        ),
    ]
